export const ADD_CHARACTER = "ADD_CHARACTER";
export const SET_CHARACTER_ORDER = "SET_CHARACTER_ORDER";
export const START_REORDER = "START_REORDER";
export const STOP_REORDER = "STOP_REORDER";
export const ORDER_UP = "ORDER_UP";
export const ORDER_DOWN = "ORDER_DOWN";
